# Generated by Django 4.2.7 on 2024-01-19 12:53

import config.storage_backends
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hairstyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('style', models.CharField(choices=[('Knotless', 'Knotless'), ('Cornrows', 'Cornrows'), ('Ponytails', 'Ponytails')], default='Knotless', max_length=100)),
                ('duration', models.FloatField(null=True)),
                ('image', models.ImageField(default='hairstyle4.jpg', storage=config.storage_backends.MediaStorage, upload_to='media/hairstyle_pictures')),
                ('description', models.TextField(default='Please ensure your hair is washed thoroughly, blow dried and grease free! - Expression Hair & Wax is provided by me!')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('size_and_price', models.CharField(choices=[('Small', 'Small'), ('S/Medium', 'S/Medium'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='Large', max_length=100)),
                ('length', models.CharField(choices=[('Bra', 'Bra'), ('Mid-Back', 'Mid-Back'), ('Waist', 'Waist'), ('Mid Thighs', 'Mid Thighs'), ('Knees', 'Knees')], default='Bra', max_length=100)),
                ('expired', models.BooleanField(default=False)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('calendar_event_id', models.CharField(max_length=500, null=True)),
                ('stripe_checkout_id', models.CharField(max_length=500, null=True)),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hairstyles', to='touchedbynoa.hairstyles')),
            ],
        ),
    ]
