# Generated by Django 4.2.7 on 2023-11-17 20:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import touchedbynoa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('client_message', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hairstyles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('time', models.FloatField(null=True)),
                ('image', models.ImageField(default='hairstyle4.jpg', upload_to='hairstyles')),
                ('description', models.TextField(default='Please ensure your hair is washed thoroughly, blow dried and grease free! - Expression Hair & Wax is provided by me!')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(choices=[(datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00')], default=datetime.time(12, 0))),
                ('size_and_price', models.CharField(choices=[('Small | £50', 'small | £50'), ('Normal | £80', 'normal | £80'), ('Large | £100', 'large | £100'), ('Extra-Large | £120', 'extra-large | £120')], default='Normal | £80', max_length=100)),
                ('length', models.CharField(choices=[('Bra', 'bra'), ('Mid-Back', 'mid-back'), ('Waist', 'waist'), ('Butt', 'butt'), ('Mid Thighs', 'mid thighs'), ('Knees', 'knees')], default='Bra', max_length=100)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(default=touchedbynoa.models.Hairstyles, on_delete=django.db.models.deletion.CASCADE, related_name='hairstyles', to='touchedbynoa.hairstyles')),
            ],
        ),
    ]
