# Generated by Django 4.2.7 on 2023-11-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyles',
            name='image',
            field=models.ImageField(default='hairstyle4.jpg', upload_to='media/profile_pics'),
        ),
    ]
