# Generated by Django 4.2.7 on 2023-11-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0003_alter_hairstyles_price_alter_hairstyles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='style_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='size', to='touchedbynoa.hairstyles'),
        ),
        migrations.AddField(
            model_name='hairstyles',
            name='style_size',
            field=models.TextField(choices=[('Small', 'small'), ('Normal', 'normal'), ('Large', 'large'), ('Extra-Large', 'extra-large')], default='Normal', max_length=50),
        ),
    ]
