# Generated by Django 4.2.7 on 2023-11-18 12:45

from django.db import migrations, models
import touchedbynoa.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0003_alter_hairstyles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyles',
            name='image',
            field=models.ImageField(default='hairstyle4.jpg', storage=touchedbynoa.storage_backends.MediaStorage, upload_to='hairstyle_pictures'),
        ),
    ]
