# Generated by Django 4.2.7 on 2023-11-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0004_appointment_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
