# Generated by Django 4.2.7 on 2023-11-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0005_appointment_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='eventID',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
