# Generated by Django 4.2.7 on 2023-11-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0005_alter_appointment_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairstyles',
            name='style_size',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='style_size',
            field=models.TextField(choices=[('Small', 'small'), ('Normal', 'normal'), ('Large', 'large'), ('Extra-Large', 'extra-large')], default='Normal', max_length=50),
        ),
    ]
