# Generated by Django 4.2.7 on 2023-11-09 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0006_remove_hairstyles_style_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '9:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '1:00'), (datetime.time(14, 0), '2:00'), (datetime.time(15, 0), '3:00'), (datetime.time(16, 0), '4:00'), (datetime.time(17, 0), '5:00')]),
        ),
    ]
