# Generated by Django 4.2.7 on 2023-11-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0008_appointment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='eventID',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
