# Generated by Django 4.2.7 on 2023-11-09 10:06

from django.db import migrations, models
import django.db.models.deletion
import touchedbynoa.models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0009_remove_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.ForeignKey(default=touchedbynoa.models.Hairstyles, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='touchedbynoa.hairstyles'),
        ),
    ]
