# Generated by Django 4.2.7 on 2023-12-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0009_alter_appointment_eventid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='stripe_checkout_id',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
