# Generated by Django 4.2.7 on 2023-11-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0010_alter_appointment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyles',
            name='time',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
