# Generated by Django 4.2.7 on 2023-12-01 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0010_appointment_payment_bool_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='payment_bool',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='stripe_checkout_id',
        ),
    ]
