# Generated by Django 4.2.7 on 2023-11-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0011_hairstyles_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyles',
            name='description',
            field=models.TextField(default='Please ensure your hair is washed thoroughly, blow dried and grease free! - Expression Hair & Wax is provided by me!'),
        ),
    ]
