# Generated by Django 4.2.7 on 2023-11-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0012_alter_hairstyles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyles',
            name='time',
            field=models.FloatField(null=True),
        ),
    ]
