# Generated by Django 4.2.7 on 2024-01-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0013_alter_appointment_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
