# Generated by Django 4.2.7 on 2023-11-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0013_alter_hairstyles_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.FloatField(default=80),
        ),
    ]
