# Generated by Django 4.2.7 on 2024-01-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0014_delete_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyles',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hairstyles', to='touchedbynoa.hairstyles'),
        ),
    ]
