# Generated by Django 4.2.7 on 2023-11-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0014_appointment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyles',
            name='style_size',
            field=models.TextField(choices=[('Small', 'small'), ('Normal', 'normal'), ('Large', 'large'), ('Extra-Large', 'extra-large')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='style_size',
            field=models.TextField(choices=[('Small', 'small'), ('Normal', 'normal'), ('Large', 'large'), ('Extra-Large', 'extra-large')], max_length=50, null=True),
        ),
    ]
