# Generated by Django 4.2.7 on 2023-11-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0015_hairstyles_style_size_alter_appointment_style_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='style_size',
        ),
        migrations.RemoveField(
            model_name='hairstyles',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hairstyles',
            name='style_size',
        ),
        migrations.AddField(
            model_name='appointment',
            name='style_and_price',
            field=models.TextField(choices=[('Small | £50', 'small | £50'), ('Normal | £80', 'normal | £80'), ('Large | £100', 'large | £100'), ('Extra-Large | £120', 'extra-large | £120')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hairstyles',
            name='style_and_price',
            field=models.TextField(choices=[('Small | £50', 'small | £50'), ('Normal | £80', 'normal | £80'), ('Large | £100', 'large | £100'), ('Extra-Large | £120', 'extra-large | £120')], max_length=50, null=True),
        ),
    ]
