# Generated by Django 4.2.7 on 2024-01-11 12:18

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0015_hairstyles_video_alter_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyles',
            name='video',
            field=models.FileField(blank=True, null=True, storage=config.storage_backends.MediaStorage, upload_to='videos/'),
        ),
    ]
