# Generated by Django 4.2.7 on 2024-01-11 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0016_alter_hairstyles_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hairstyles',
            name='video',
        ),
    ]
