# Generated by Django 4.2.7 on 2024-01-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0017_remove_hairstyles_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
