# Generated by Django 4.2.7 on 2024-01-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0018_alter_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hairstyles',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
