# Generated by Django 4.2.7 on 2023-11-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0018_alter_appointment_style_and_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='style_and_price',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
