# Generated by Django 4.2.7 on 2024-01-17 17:04

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0019_alter_hairstyles_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='image',
            field=models.ImageField(default='hairstyle4.jpg', storage=config.storage_backends.MediaStorage, upload_to='media/hairstyle_pictures'),
        ),
    ]
