# Generated by Django 4.2.7 on 2024-01-18 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0020_appointment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='price',
        ),
    ]
