# Generated by Django 4.2.7 on 2024-01-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0021_remove_appointment_image_remove_appointment_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='length',
            field=models.CharField(choices=[('Bra', 'Bra'), ('Mid-Back', 'Mid-Back'), ('Waist', 'Waist'), ('Mid Thighs', 'Mid Thighs'), ('Knees', 'Knees')], default='Bra', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='size_and_price',
            field=models.CharField(choices=[('Small (£150)', 'Small (£150)'), ('S/Medium (£100)', 'S/Medium (£100)'), ('Medium (£80)', 'Medium (£80)'), ('Large (£60)', 'Large (£60)'), ('Extra Large (£45)', 'Extra Large (£45)')], default='S/Medium (£100)', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hairstyles', to='touchedbynoa.hairstyles'),
        ),
        migrations.AlterField(
            model_name='hairstyles',
            name='duration',
            field=models.FloatField(null=True),
        ),
    ]
