# Generated by Django 4.2.7 on 2023-11-11 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0022_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='client_message',
        ),
    ]
