# Generated by Django 4.2.7 on 2024-01-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0022_alter_appointment_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
