# Generated by Django 4.2.7 on 2023-11-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0023_rename_message_contact_client_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('client_message', models.TextField()),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
