# Generated by Django 4.2.7 on 2023-11-13 19:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import touchedbynoa.models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0024_contactus_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyles',
            name='image',
            field=models.ImageField(default='hairstyle4.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.ForeignKey(default=touchedbynoa.models.Hairstyles, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_name', to='touchedbynoa.hairstyles'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(choices=[(datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00')]),
        ),
    ]
