# Generated by Django 4.2.7 on 2024-01-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0024_alter_appointment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='size_and_price',
            field=models.CharField(choices=[('Small (£150)', 'Small (£150)'), ('S/Medium (£100)', 'S/Medium (£100)'), ('Medium (£80)', 'Medium (£80)'), ('Large (£60)', 'Large (£60)'), ('Extra Large (£45)', 'Extra Large (£45)')], default='Large (£60)', max_length=100),
        ),
    ]
