# Generated by Django 4.2.7 on 2023-11-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0025_hairstyles_image_alter_appointment_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='hairstyles',
            name='image',
            field=models.ImageField(default='hairstyle4.jpg', upload_to='media/profile_pics'),
        ),
    ]
