# Generated by Django 4.2.7 on 2024-01-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0026_alter_appointment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hairstyles',
            name='style',
            field=models.CharField(choices=[('Knotless', 'Knotless'), ('Cornrows', 'Cornrows'), ('Ponytails', 'Ponytails')], default='Knotless', max_length=100),
        ),
    ]
