# Generated by Django 4.2.7 on 2024-01-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0027_hairstyles_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='size_and_price',
            field=models.CharField(choices=[('Small', 'Small'), ('S/Medium', 'S/Medium'), ('Medium', 'Medium'), ('Large', 'Large'), ('Extra Large', 'Extra Large')], default='Large', max_length=100),
        ),
    ]
