# Generated by Django 4.2.7 on 2023-11-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0027_remove_appointment_style_and_price_appointment_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='size',
            field=models.CharField(choices=[('Small', 'small'), ('Normal | £80', 'normal'), ('Large', 'large'), ('Extra-Large', 'extra-large')], default='Normal | £80', max_length=100),
        ),
    ]
