# Generated by Django 4.2.7 on 2023-11-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0030_appointment_length_alter_appointment_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='price',
            field=models.PositiveIntegerField(choices=[(50, 50), (80, 80), (100, 100), (120, 120)], default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='length',
            field=models.CharField(choices=[('Bra', 'bra'), ('Mid-Back', 'mid-back'), ('Waist', 'waist'), ('Butt', 'butt'), ('Mid Thighs', 'mid thighs'), ('Knees', 'knees')], default='Bra', max_length=100),
        ),
    ]
