# Generated by Django 4.2.7 on 2023-11-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0031_appointment_price_alter_appointment_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='price',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=10),
        ),
    ]
