# Generated by Django 4.2.7 on 2023-11-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0032_alter_appointment_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='size',
        ),
        migrations.AddField(
            model_name='appointment',
            name='size_and_price',
            field=models.CharField(choices=[('Small | £50', 'small| £50'), ('Normal| £80', 'normal| £80'), ('Large| £100', 'large| £100'), ('Extra-Large| £120', 'extra-large| £120')], default='Normal| £80', max_length=100),
        ),
    ]
