# Generated by Django 4.2.7 on 2023-11-17 20:30

from django.db import migrations, models
import django.db.models.deletion
import touchedbynoa.models


class Migration(migrations.Migration):

    dependencies = [
        ('touchedbynoa', '0035_alter_appointment_size_and_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='title',
            field=models.ForeignKey(default=touchedbynoa.models.Hairstyles, on_delete=django.db.models.deletion.CASCADE, related_name='hairstyles', to='touchedbynoa.hairstyles'),
        ),
        migrations.AlterField(
            model_name='hairstyles',
            name='image',
            field=models.ImageField(default=touchedbynoa.models.default_hairstyle, upload_to=touchedbynoa.models.default_image_path),
        ),
    ]
